# .github/workflows/reg.yml

name: reg-suit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: yarn install
      run: |
        yarn
    - name: workaround for detached HEAD
      run: |
        git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
#     - name: run storycap
#       run: |
#         yarn run storycap
    - name: run reg-suit
      run: |
        npx reg-suit run
